.\"     Title: pam_access
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets vsnapshot_2006\-08\-24_0226 <http://docbook.sf.net/>
.\"      Date: 08/31/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_ACCESS" "8" "08/31/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_access \- PAM module for logdaemon style login access control
.SH "SYNOPSIS"
.HP 14
\fBpam_access.so\fR [debug] [accessfile=\fIfile\fR] [fieldsep=\fIsep\fR] [listsep=\fIsep\fR]
.SH "DESCRIPTION"
.PP
The pam_access PAM module is mainly for access management. It provides logdaemon style login access control based on login names, host or domain names, internet addresses or network numbers, or on terminal line names in case of non\-networked logins.
.PP
By default rules for access management are taken from config file
\fI/etc/security/access.conf\fR
if you don't specify another file.
.SH "OPTIONS"
.TP 3n
\fBaccessfile=\fR\fB\fI/path/to/access.conf\fR\fR
Indicate an alternative
\fIaccess.conf\fR
style configuration file to override the default. This can be useful when different services need different access lists.
.TP 3n
\fBdebug\fR
A lot of debug informations are printed with
\fBsyslog\fR(3).
.TP 3n
\fBfieldsep=\fR\fB\fIseparators\fR\fR
This option modifies the field separator character that pam_access will recognize when parsing the access configuration file. For example:
\fBfieldsep=|\fR
will cause the default `:' character to be treated as part of a field value and `|' becomes the field separator. Doing this may be useful in conjuction with a system that wants to use pam_access with X based applications, since the
\fBPAM_TTY\fR
item is likely to be of the form "hostname:0" which includes a `:' character in its value. But you should not need this.
.TP 3n
\fBlistsep=\fR\fB\fIseparators\fR\fR
This option modifies the list separator character that pam_access will recognize when parsing the access configuration file. For example:
\fBlistsep=,\fR
will cause the default ` ' (space) and `\\t' (tab) characters to be treated as part of a list element value and `,' becomes the only list element separator. Doing this may be useful on a system with group information obtained from a Windows domain, where the default built\-in groups "Domain Users", "Domain Admins" contain a space.
.SH "MODULE SERVICES PROVIDED"
.PP
All services are supported.
.SH "RETURN VALUES"
.TP 3n
PAM_SUCCESS
Access was granted.
.TP 3n
PAM_PERM_DENIED
Access was not granted.
.TP 3n
PAM_IGNORE

\fBpam_setcred\fR
was called which does nothing.
.TP 3n
PAM_ABORT
Not all relevant data or options could be gotten.
.TP 3n
PAM_USER_UNKNOWN
The user is not known to the system.
.SH "FILES"
.TP 3n
\fI/etc/security/access.conf\fR
Default configuration file
.SH "SEE ALSO"
.PP

\fBaccess.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8).
.SH "AUTHORS"
.PP
The logdaemon style login access control scheme was designed and implemented by Wietse Venema. The pam_access PAM module was developed by Alexei Nogin <alexei@nogin.dnttm.ru>. The IPv6 support and the network(address) / netmask feature was developed and provided by Mike Becher <mike.becher@lrz\-muenchen.de>.
