.\" Copyright (C) 2003 International Business Machines Corporation
.\" This file is distributed according to the GNU General Public License.
.\" See the file COPYING in the top level source directory for details.
.\"
.de Sh \" Subsection
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.de Ip \" List item
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.TH "UNIX_CHKPWD" 8 "2003-03-21" "Linux-PAM 0.76" "Linux-PAM Manual"
.SH NAME
unix_chkpwd \- helper binary that verifies the password of the current user
.SH "SYNOPSIS"
.ad l
.hy 0

/sbin/unix_chkpwd [\fIusername\fR]
.sp
.ad
.hy
.SH "DESCRIPTION"
.PP
\fBunix_chkpwd\fR is a helper program for the pam_unix module that verifies 
the password of the current user.  It is not intended to be run directly from 
the command line and logs a security violation if done so. 

It is typically installed setuid root or setgid shadow.

.SH "OPTIONS"
.PP
unix_pwdchk optionally takes the following argument:
.TP
\fIusername\fR
The username of the user whose password you want to check: this must match the current user id.	

.SH "INPUTS"
.PP
unix_pwdchk expects the following inputs via stdin:
.TP
\fIoption\fR
Either nullok or nonull, depending on whether the user can have an empty password.
.TP
\fIpassword\fR
The password to verify.

.SH "RETURN CODES"
.PP
\fBunix_chkpwd\fR has the following return codes:
.TP
1
unix_chkpwd was inappropriately called from the command line or the password is incorrect.

.TP
0
The password is correct.

.SH "HISTORY"
Written by Andrew Morgan

.SH "SEE ALSO"

.PP
\fBpam\fR(8)

.SH AUTHOR
Emily Ratliff.

