.\"     Title: pam_time
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 01/07/2008
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"
.TH "PAM_TIME" "8" "01/07/2008" "Linux-PAM Manual" "Linux-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_time - PAM module for time control access
.SH "SYNOPSIS"
.HP 12
\fBpam_time\.so\fR [debug] [noaudit]
.SH "DESCRIPTION"
.PP
The pam_time PAM module does not authenticate the user, but instead it restricts access to a system and or specific applications at various times of the day and on specific days or over various terminal lines\. This module can be configured to deny access to (individual) users based on their name, the time of day, the day of week, the service they are applying for and their terminal from which they are making their request\.
.PP
By default rules for time/port access are taken from config file
\fI/etc/security/time\.conf\fR\.
.PP
If Linux PAM is compiled with audit support the module will report when it denies access\.
.SH "OPTIONS"
.PP
\fBdebug\fR
.RS 4
Some debug informations are printed with
\fBsyslog\fR(3)\.
.RE
.PP
\fBnoaudit\fR
.RS 4
Do not report logins at disallowed time to the audit subsystem\.
.RE
.SH "MODULE SERVICES PROVIDED"
.PP
Only the
\fBaccount\fR
service is supported\.
.SH "RETURN VALUES"
.PP
PAM_SUCCESS
.RS 4
Access was granted\.
.RE
.PP
PAM_ABORT
.RS 4
Not all relevant data could be gotten\.
.RE
.PP
PAM_BUF_ERR
.RS 4
Memory buffer error\.
.RE
.PP
PAM_PERM_DENIED
.RS 4
Access was not granted\.
.RE
.PP
PAM_USER_UNKNOWN
.RS 4
The user is not known to the system\.
.RE
.SH "FILES"
.PP
\fI/etc/security/time\.conf\fR
.RS 4
Default configuration file
.RE
.SH "EXAMPLES"
.sp
.RS 4
.nf
#%PAM\-1\.0
#
# apply pam_time accounting to login requests
#
login  account  required  pam_time\.so
      
.fi
.RE
.SH "SEE ALSO"
.PP

\fBtime.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)\.
.SH "AUTHOR"
.PP
pam_time was written by Andrew G\. Morgan <morgan@kernel\.org>\.
