.\"     Title: group.conf
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/21/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "GROUP.CONF" "5" "06/21/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
group.conf \- configuration file for the pam_group module
.SH "DESCRIPTION"
.PP
The pam_group PAM module does not authenticate the user, but instead it grants group memberships (in the credential setting phase of the authentication module) to the user. Such memberships are based on the service they are applying for.
.PP
For this module to function correctly there must be a correctly formatted
\fI/etc/security/group.conf\fR
file present. White spaces are ignored and lines maybe extended with '\\' (escaped newlines). Text following a '#' is ignored to the end of the line.
.PP
The syntax of the lines is as follows:
.PP

\fIservices\fR;\fIttys\fR;\fIusers\fR;\fItimes\fR;\fIgroups\fR
.PP
The first field, the
\fIservices\fR
field, is a logic list of PAM service names that the rule applies to.
.PP
The second field, the
\fItty\fR
field, is a logic list of terminal names that this rule applies to.
.PP
The third field, the
\fIusers\fR
field, is a logic list of users or a netgroup of users to whom this rule applies.
.PP
For these items the simple wildcard '*' may be used only once. With netgroups no wildcards or logic operators are allowed.
.PP
The
\fItimes\fR
field is used to indicate "when" these groups are to be given to the user. The format here is a logic list of day/time\-range entries. The days are specified by a sequence of two character entries, MoTuSa for example is Monday Tuesday and Saturday. Note that repeated days are unset MoMo = no day, and MoWk = all weekdays bar Monday. The two character combinations accepted are Mo Tu We Th Fr Sa Su Wk Wd Al, the last two being week\-end days and all 7 days of the week respectively. As a final example, AlFr means all days except Friday.
.PP
Each day/time\-range can be prefixed with a '!' to indicate "anything but". The time\-range part is two 24\-hour times HHMM, separated by a hyphen, indicating the start and finish time (if the finish time is smaller than the start time it is deemed to apply on the following day).
.PP
The
\fIgroups\fR
field is a comma or space separated list of groups that the user inherits membership of. These groups are added if the previous fields are satisfied by the user's request.
.PP
For a rule to be active, ALL of service+ttys+users must be satisfied by the applying process.
.SH "EXAMPLES"
.PP
These are some example lines which might be specified in
\fI/etc/security/group.conf\fR.
.PP
Running 'xsh' on tty* (any ttyXXX device), the user 'us' is given access to the floppy (through membership of the floppy group)
.sp
.RS 3n
.nf
xsh;tty*&!ttyp*;us;Al0000\-2400;floppy
.fi
.RE
.PP
Running 'xsh' on tty* (any ttyXXX device), the user 'sword' is given access to games (through membership of the floppy group) after work hours.
.sp
.RS 3n
.nf
xsh; tty* ;sword;!Wk0900\-1800;games, sound
xsh; tty* ;*;Al0900\-1800;floppy
    
.fi
.RE
.SH "SEE ALSO"
.PP

\fBpam_group\fR(8),
\fBpam.d\fR(5),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_group was written by Andrew G. Morgan <morgan@kernel.org>.
