.\"     Title: pam_deny
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/21/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_DENY" "8" "06/21/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_deny \- The locking\-out PAM module
.SH "SYNOPSIS"
.HP 12
\fBpam_deny.so\fR
.SH "DESCRIPTION"
.PP
This module can be used to deny access. It always indicates a failure to the application through the PAM framework. It might be suitable for using for default (the
\fIOTHER\fR) entries.
.SH "OPTIONS"
.PP
This module does not recognice any options.
.SH "MODULE SERVICES PROVIDED"
.PP
All services (\fBaccount\fR,
\fBauth\fR,
\fBpassword\fR
and
\fBsession\fR) are supported.
.SH "RETURN VALUES"
.PP
.TP 3n
PAM_AUTH_ERR
This is returned by the account and auth services.
.TP 3n
PAM_CRED_ERR
This is returned by the setcred function.
.TP 3n
PAM_AUTHTOK_ERR
This is returned by the password service.
.TP 3n
PAM_SESSION_ERR
This is returned by the session service.
.SH "EXAMPLES"
.sp
.RS 3n
.nf
#%PAM\-1.0
#
# If we don't have config entries for a service, the
# OTHER entries are used. To be secure, warn and deny
# access to everything.
other auth     required       pam_warn.so
other auth     required       pam_deny.so
other account  required       pam_warn.so
other account  required       pam_deny.so
other password required       pam_warn.so
other password required       pam_deny.so
other session  required       pam_warn.so
other session  required       pam_deny.so
    
.fi
.RE
.SH "SEE ALSO"
.PP

\fBpam.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_deny was written by Andrew G. Morgan <morgan@kernel.org>
