.\"     Title: pam_mkhomedir
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/02/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_MKHOMEDIR" "8" "06/02/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_mkhomedir \- PAM module to create users home directory
.SH "SYNOPSIS"
.HP 17
\fBpam_mkhomedir.so\fR [silent] [umask=\fImode\fR] [skel=\fIskeldir\fR]
.SH "DESCRIPTION"
.PP
The pam_mkhomedir PAM module will create a users home directory if it does not exist when the session begins. This allows users to be present in central database (such as NIS, kerberos or LDAP) without using a distributed file system or pre\-creating a large number of directories. The skeleton directory (usually
\fI/etc/skel/\fR) is used to copy default files and also set's a umask for the creation.
.PP
The new users home directory will not be removed after logout of the user.
.SH "OPTIONS"
.TP 3n
\fBsilent\fR
Don't print informative messages.
.TP 3n
\fBumask=\fR\fB\fImask\fR\fR
The user file\-creation mask is set to
\fImask\fR. The default value of mask is 0022.
.TP 3n
\fBskel=\fR\fB\fI/path/to/skel/directory\fR\fR
Indicate an alternative
\fIskel\fR
directory to override the default
\fI/etc/skel\fR.
.SH "MODULE SERVICES PROVIDED"
.PP
Only the
\fBsession\fR
service is supported.
.SH "RETURN VALUES"
.TP 3n
PAM_BUF_ERR
Memory buffer error.
.TP 3n
PAM_CRED_INSUFFICIENT
Insufficient credentials to access authentication data.
.TP 3n
PAM_PERM_DENIED
Not enough permissions to create the new directory or read the skel directory.
.TP 3n
PAM_USER_UNKNOWN
User not known to the underlying authentication module.
.TP 3n
PAM_SUCCESS
Environment variables were set.
.SH "FILES"
.TP 3n
\fI/etc/skel\fR
Default skel directory
.SH "EXAMPLES"
.PP
A sample /etc/pam.d/login file:
.sp
.RS 3n
.nf
  auth       requisite   pam_securetty.so
  auth       sufficient  pam_ldap.so
  auth       required    pam_unix.so
  auth       required    pam_nologin.so
  account    sufficient  pam_ldap.so
  account    required    pam_unix.so
  password   required    pam_unix.so
  session    required    pam_mkhomedir.so skel=/etc/skel/ umask=0022
  session    required    pam_unix.so
  session    optional    pam_lastlog.so
  session    optional    pam_mail.so standard
      
.fi
.RE
.sp
.SH "SEE ALSO"
.PP

\fBpam.d\fR(8),
\fBpam\fR(8).
.SH "AUTHOR"
.PP
pam_mkhomedir was written by Jason Gunthorpe <jgg@debian.org>.
