.\"     Title: pam
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 10/26/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM" "3" "10/26/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam \- Pluggable Authentication Modules Library
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_appl.h>
.fi
.ft
.sp
.ft B
.nf
#include <security/pam_modules.h>
.fi
.ft
.sp
.ft B
.nf
#include <security/pam_ext.h>
.fi
.ft
.SH "DESCRIPTION"
.PP

\fBPAM\fR
is a system of libraries that handle the authentication tasks of applications (services) on the system. The library provides a stable general interface (Application Programming Interface \- API) that privilege granting programs (such as
\fBlogin\fR(1)
and
\fBsu\fR(1)) defer to to perform standard authentication tasks.
.SS "Initialization and Cleanup"
.PP
The
\fBpam_start\fR(3)
function creates the PAM context and initiates the PAM transaction. It is the first of the PAM functions that needs to be called by an application. The transaction state is contained entirely within the structure identified by this handle, so it is possible to have multiple transactions in parallel. But it is not possible to use the same handle for different transactions, a new one is needed for every new context.
.PP
The
\fBpam_end\fR(3)
function terminates the PAM transaction and is the last function an application should call in the PAM context. Upon return the handle pamh is no longer valid and all memory associated with it will be invalid. It can be called at any time to terminate a PAM transaction.
.SS "Authentication"
.PP
The
\fBpam_authenticate\fR(3)
function is used to authenticate the user. The user is required to provide an authentication token depending upon the authentication service, usually this is a password, but could also be a finger print.
.PP
The
\fBpam_setcred\fR(3)
function manages the userscredentials.
.SS "Account Management"
.PP
The
\fBpam_acct_mgmt\fR(3)
function is used to determine if the users account is valid. It checks for authentication token and account expiration and verifies access restrictions. It is typically called after the user has been authenticated.
.SS "Password Management"
.PP
The
\fBpam_chauthtok\fR(3)
function is used to change the authentication token for a given user on request or because the token has expired.
.SS "Session Management"
.PP
The
\fBpam_open_session\fR(3)
function sets up a user session for a previously successful authenticated user. The session should later be terminated with a call to
\fBpam_close_session\fR(3).
.SS "Conversation"
.PP
The PAM library uses an application\-defined callback to allow a direct communication between a loaded module and the application. This callback is specified by the
\fIstruct pam_conv\fR
passed to
\fBpam_start\fR(3)
at the start of the transaction. See
\fBpam_conv\fR(3)
for details.
.SS "Data Objects"
.PP
The
\fBpam_set_item\fR(3)
and
\fBpam_get_item\fR(3)
functions allows applications and PAM service modules to set and retrieve PAM informations.
.PP
The
\fBpam_get_user\fR(3)
function is the preferred method to obtain the username.
.PP
The
\fBpam_set_data\fR(3)
and
\fBpam_get_data\fR(3)
functions allows PAM service modules to set and retrieve free\-form data from one invocation to another.
.SS "Environment and Error Management"
.PP
The
\fBpam_putenv\fR(3),
\fBpam_getenv\fR(3)
and
\fBpam_getenvlist\fR(3)
functions are for maintaining a set of private environment variables.
.PP
The
\fBpam_strerror\fR(3)
function returns a pointer to a string describing the given PAM error code.
.SH "RETURN VALUES"
.PP
The following return codes are known by PAM:
.PP
PAM_ABORT
.RS 3n
Critical error, immediate abort.
.RE
.PP
PAM_ACCT_EXPIRED
.RS 3n
User account has expired.
.RE
.PP
PAM_AUTHINFO_UNAVAIL
.RS 3n
Authentication service cannot retrieve authentication info.
.RE
.PP
PAM_AUTHTOK_DISABLE_AGING
.RS 3n
Authentication token aging disabled.
.RE
.PP
PAM_AUTHTOK_ERR
.RS 3n
Authentication token manipulation error.
.RE
.PP
PAM_AUTHTOK_EXPIRED
.RS 3n
Authentication token expired.
.RE
.PP
PAM_AUTHTOK_LOCK_BUSY
.RS 3n
Authentication token lock busy.
.RE
.PP
PAM_AUTHTOK_RECOVERY_ERR
.RS 3n
Authentication information cannot be recovered.
.RE
.PP
PAM_AUTH_ERR
.RS 3n
Authentication failure.
.RE
.PP
PAM_BUF_ERR
.RS 3n
Memory buffer error.
.RE
.PP
PAM_CONV_ERR
.RS 3n
Conversation failure.
.RE
.PP
PAM_CRED_ERR
.RS 3n
Failure setting user credentials.
.RE
.PP
PAM_CRED_EXPIRED
.RS 3n
User credentials expired.
.RE
.PP
PAM_CRED_INSUFFICIENT
.RS 3n
Insufficient credentials to access authentication data.
.RE
.PP
PAM_CRED_UNAVAIL
.RS 3n
Authentication service cannot retrieve user credentials.
.RE
.PP
PAM_IGNORE
.RS 3n
The return value should be ignored by PAM dispatch.
.RE
.PP
PAM_MAXTRIES
.RS 3n
Have exhausted maximum number of retries for service.
.RE
.PP
PAM_MODULE_UNKNOWN
.RS 3n
Module is unknown.
.RE
.PP
PAM_NEW_AUTHTOK_REQD
.RS 3n
Authentication token is no longer valid; new one required.
.RE
.PP
PAM_NO_MODULE_DATA
.RS 3n
No module specific data is present.
.RE
.PP
PAM_OPEN_ERR
.RS 3n
Failed to load module.
.RE
.PP
PAM_PERM_DENIED
.RS 3n
Permission denied.
.RE
.PP
PAM_SERVICE_ERR
.RS 3n
Error in service module.
.RE
.PP
PAM_SESSION_ERR
.RS 3n
Cannot make/remove an entry for the specified session.
.RE
.PP
PAM_SUCCESS
.RS 3n
Success.
.RE
.PP
PAM_SYMBOL_ERR
.RS 3n
Symbol not found.
.RE
.PP
PAM_SYSTEM_ERR
.RS 3n
System error.
.RE
.PP
PAM_TRY_AGAIN
.RS 3n
Failed preliminary check by password service.
.RE
.PP
PAM_USER_UNKNOWN
.RS 3n
User not known to the underlying authentication module.
.RE
.SH "SEE ALSO"
.PP

\fBpam_acct_mgmt\fR(3),
\fBpam_authenticate\fR(3),
\fBpam_chauthtok\fR(3),
\fBpam_close_session\fR(3),
\fBpam_conv\fR(3),
\fBpam_end\fR(3),
\fBpam_get_data\fR(3),
\fBpam_getenv\fR(3),
\fBpam_getenvlist\fR(3),
\fBpam_get_item\fR(3),
\fBpam_get_user\fR(3),
\fBpam_open_session\fR(3),
\fBpam_putenv\fR(3),
\fBpam_set_data\fR(3),
\fBpam_set_item\fR(3),
\fBpam_setcred\fR(3),
\fBpam_start\fR(3),
\fBpam_strerror\fR(3)
