.\"     Title: pam_chauthtok
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_CHAUTHTOK" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_chauthtok \- updating authentication tokens
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_appl.h>
.fi
.ft
.HP 18
.BI "int pam_chauthtok(pam_handle_t\ *" "pamh" ", int\ " "flags" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_chauthtok\fR
function is used to change the authentication token for a given user (as indicated by the state associated with the handle
\fIpamh\fR).
.PP
The
\fIpamh\fR
argument is an authentication handle obtained by a prior call to pam_start(). The flags argument is the binary or of zero or more of the following values:
.TP 3n
PAM_SILENT
Do not emit any messages.
.TP 3n
PAM_CHANGE_EXPIRED_AUTHTOK
This argument indicates to the modules that the users authentication token (password) should only be changed if it has expired. If this argument is not passed, the application requires that all authentication tokens are to be changed.
.SH "RETURN VALUES"
.TP 3n
PAM_AUTHTOK_ERR
A module was unable to obtain the new authentication token.
.TP 3n
PAM_AUTHTOK_RECOVERY_ERR
A module was unable to obtain the old authentication token.
.TP 3n
PAM_AUTHTOK_LOCK_BUSY
One or more of the modules was unable to change the authentication token since it is currently locked.
.TP 3n
PAM_AUTHTOK_DISABLE_AGING
Authentication token aging has been disabled for at least one of the modules.
.TP 3n
PAM_PERM_DENIED
Permission denied.
.TP 3n
PAM_SUCCESS
The authentication token was successfully updated.
.TP 3n
PAM_TRY_AGAIN
Not all of the modules were in a position to update the authentication token(s). In such a case none of the user's authentication tokens are updated.
.TP 3n
PAM_USER_UNKNOWN
User unknown to password service.
.SH "SEE ALSO"
.PP

\fBpam_start\fR(3),
\fBpam_authenticate\fR(3),
\fBpam_setcred\fR(3),
\fBpam_get_item\fR(3),
\fBpam_strerror\fR(3),
\fBpam\fR(8)
