.\"     Title: pam_misc_setenv
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_MISC_SETENV" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_misc_setenv \- BSD like PAM environment variable setting
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_misc.h>
.fi
.ft
.HP 20
.BI "int pam_misc_setenv(pam_handle_t\ *" "pamh" ", const\ char\ *" "name" ", const\ char\ *" "value" ", int" "readonly" ");"
.SH "DESCRIPTION"
.PP
This function performs a task equivalent to
\fBpam_putenv\fR(3), its syntax is, however, more like the BSD style function;
\fBsetenv()\fR. The
\fIname\fR
and
\fIvalue\fR
are concatenated with an '=' to form a name=value and passed to
\fBpam_putenv()\fR. If, however, the PAM variable is already set, the replacement will only be applied if the last argument,
\fIreadonly\fR, is zero.
.SH "SEE ALSO"
.PP

\fBpam_putenv\fR(3),
\fBpam\fR(8)
.SH "STANDARDS"
.PP
The
\fBpam_misc_setenv\fR
function is part of the
\fBlibpam_misc\fR
Library and not defined in any standard.
