.\"     Title: pam_sm_open_session
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_SM_OPEN_SESSION" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_sm_open_session \- PAM service function to start session management
.SH "SYNOPSIS"
.sp
.ft B
.nf
#define PAM_SM_SESSION
.fi
.ft
.sp
.ft B
.nf
#include <security/pam_modules.h>
.fi
.ft
.HP 35
.BI "PAM_EXTERN int pam_sm_open_session(pam_handle_t\ *" "pamh" ", int\ " "flags" ", int\ " "argc" ", const\ char\ **" "argv" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_sm_open_session\fR
function is the service module's implementation of the
\fBpam_open_session\fR(3)
interface.
.PP
This function is called to commence a session. The only valid value for
\fIflags\fR
is zero or:
.TP 3n
PAM_SILENT
Do not emit any messages.
.SH "RETURN VALUES"
.TP 3n
PAM_SESSION_ERR
Cannot make/remove an entry for the specified session.
.TP 3n
PAM_SUCCESS
The session was successfully started.
.SH "SEE ALSO"
.PP

\fBpam\fR(3),
\fBpam_open_session\fR(3),
\fBpam_sm_close_session\fR(3),
\fBpam_strerror\fR(3),
\fBPAM\fR(8)
