.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "PAM_CLOSE_SESSION" "3" "05/04/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_close_session \- terminating PAM session management
.SH "SYNOPSIS"
.PP
\fB#include <security/pam_appl.h>\fR
.HP 22
\fBint\ \fBpam_close_session\fR\fR\fB(\fR\fBpam_handle_t\ *\fR\fB\fIpamh\fR\fR\fB, \fR\fBint\ \fR\fB\fIflags\fR\fR\fB);\fR
.SH "DESCRIPTION"
.PP
The
\fBpam_close_session\fR
function is used to indicate that an authenticated session has ended. The session should have been created with a call to
\fBpam_open_session\fR(3).
.PP
It should be noted that the effective uid,
\fBgeteuid\fR(2). of the application should be of sufficient privilege to perform such tasks as unmounting the user's home directory for example.
.PP
The flags argument is the binary or of zero or more of the following values:
.TP
PAM_SILENT
Do not emit any messages.
.SH "RETURN VALUES"
.TP
PAM_ABORT
General failure.
.TP
PAM_BUF_ERR
Memory buffer error.
.TP
PAM_SESSION_ERR
Session failure.
.TP
PAM_SUCCESS
Session was successful terminated.
.SH "SEE ALSO"
.PP
\fBpam_open_session\fR(3),
\fBpam_strerror\fR(3)
