.\"     Title: pam_error
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_ERROR" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_error, pam_verror \- display error messages to the user
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_ext.h>
.fi
.ft
.HP 14
.BI "int pam_error(pam_handle_t\ *" "pamh" ", const\ char\ *" "fmt" ", " "..." ");"
.HP 15
.BI "int pam_verror(pam_handle_t\ *" "pamh" ", const\ char\ *" "fmt" ", va_list\ " "args" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_error\fR
function prints error messages through the conversation function to the user.
.PP
The
\fBpam_verror\fR
function performs the same task as
\fBpam_error()\fR
with the difference that it takes a set of arguments which have been obtained using the
\fBstdarg\fR(3)
variable argument list macros.
.SH "RETURN VALUES"
.TP 3n
PAM_BUF_ERR
Memory buffer error.
.TP 3n
PAM_CONV_ERR
Conversation failure.
.TP 3n
PAM_SUCCESS
Error message was displayed.
.TP 3n
PAM_SYSTEM_ERR
System error.
.SH "SEE ALSO"
.PP

\fBpam_info\fR(3),
\fBpam_vinfo\fR(3),
\fBpam_prompt\fR(3),
\fBpam_vprompt\fR(3),
\fBpam\fR(8)
.SH "STANDARDS"
.PP
The
\fBpam_error\fR
and
\fBpam_verror\fR
functions are Linux\-PAM extensions.
