.\"     Title: pam_prompt
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_PROMPT" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_prompt, pam_vprompt \- interface to conversation function
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_ext.h>
.fi
.ft
.HP 16
.BI "void pam_prompt(pam_handle_t\ *" "pamh" ", int\ " "style" ", char\ **" "response" ", const\ char\ *" "fmt" ", " "..." ");"
.HP 17
.BI "void pam_vprompt(pam_handle_t\ *" "pamh" ", int\ " "style" ", char\ **" "response" ", const\ char\ *" "fmt" ", va_list\ " "args" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_prompt\fR
function constructs a message from the specified format string and arguments and passes it to
.SH "RETURN VALUES"
.TP 3n
PAM_BUF_ERR
Memory buffer error.
.TP 3n
PAM_CONV_ERR
Conversation failure.
.TP 3n
PAM_SUCCESS
Transaction was successful created.
.TP 3n
PAM_SYSTEM_ERR
System error.
.SH "SEE ALSO"
.PP

\fBpam\fR(8),
\fBpam_conv\fR(3)
.SH "STANDARDS"
.PP
The
\fBpam_prompt\fR
and
\fBpam_vprompt\fR
functions are Linux\-PAM extensions.
