.\"     Title: pam_misc_paste_env
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_MISC_PASTE_ENV" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_misc_paste_env \- transcribing an environment to that of PAM
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_misc.h>
.fi
.ft
.HP 23
.BI "int pam_misc_paste_env(pam_handle_t\ *" "pamh" ", const\ char\ *\ const\ *" "user" ");"
.SH "DESCRIPTION"
.PP
This function takes the supplied list of environment pointers and
\fIuploads\fR
its contents to the PAM environment. Success is indicated by
PAM_SUCCESS.
.SH "SEE ALSO"
.PP

\fBpam_putenv\fR(3),
\fBpam\fR(8)
.SH "STANDARDS"
.PP
The
\fBpam_misc_paste_env\fR
function is part of the
\fBlibpam_misc\fR
Library and not defined in any standard.
