.\"     Title: pam_getenv
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_GETENV" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_getenv \- get a PAM environment variable
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_appl.h>
.fi
.ft
.HP 23
.BI "const char *pam_getenv(pam_handle_t\ *" "pamh" ", const\ char\ *" "name" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_getenv\fR
function searches the PAM environment list as associated with the handle
\fIpamh\fR
for a string that matches the string pointed to by
\fIname\fR. The return values are of the form: "\fIname=value\fR".
.SH "RETURN VALUES"
.PP
The
\fBpam_getenv\fR
function returns NULL on failure.
.SH "SEE ALSO"
.PP

\fBpam_start\fR(3),
\fBpam_getenvlist\fR(3),
\fBpam_putenv\fR(3),
\fBpam\fR(8)
