.\"     Title: pam_get_user
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_GET_USER" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_get_user \- get user name
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_modules.h>
.fi
.ft
.HP 17
.BI "int pam_get_user(const\ pam_handle_t\ *" "pamh" ", const\ char\ **" "user" ", const\ char\ *" "prompt" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_get_user\fR
function returns the name of the user specified by
\fBpam_start\fR(3). If no user was specified it what
\fBpam_get_item (pamh, PAM_USER, ... );\fR
would have returned. If this is NULL it obtains the username via the
\fBpam_conv\fR(3)
mechanism, it prompts the user with the first non\-NULL string in the following list:
.TP 3n
\(bu
The
\fIprompt\fR
argument passed to the function.
.TP 3n
\(bu
What is returned by pam_get_item (pamh, PAM_USER_PROMPT, ... );
.TP 3n
\(bu
The default prompt: "login: "
.sp
.RE
.PP
By whatever means the username is obtained, a pointer to it is returned as the contents of
\fI*user\fR. Note, this memory should
\fBnot\fR
be
\fIfree()\fR'd or
\fImodified\fR
by the module.
.PP
This function sets the
\fIPAM_USER\fR
item associated with the
\fBpam_set_item\fR(3)
and
\fBpam_get_item\fR(3)
functions.
.SH "RETURN VALUES"
.TP 3n
PAM_SUCCESS
User name was successful retrieved.
.TP 3n
PAM_SYSTEM_ERR
A NULL pointer was submitted.
.TP 3n
PAM_CONV_ERR
The conversation method supplied by the application failed to obtain the username.
.SH "SEE ALSO"
.PP

\fBpam_end\fR(3),
\fBpam_get_item\fR(3),
\fBpam_set_item\fR(3),
\fBpam_strerror\fR(3)
