.\"     Title: pam_syslog
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_SYSLOG" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_syslog, pam_vsyslog \- send messages to the system logger
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <syslog.h>
.fi
.ft
.sp
.ft B
.nf
#include <security/pam_ext.h>
.fi
.ft
.HP 16
.BI "void pam_syslog(pam_handle_t\ *" "pamh" ", int\ " "priority" ", const\ char\ *" "fmt" ", " "..." ");"
.HP 17
.BI "void pam_vsyslog(pam_handle_t\ *" "pamh" ", int\ " "priority" ", const\ char\ *" "fmt" ", va_list\ " "args" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_syslog\fR
function logs messages using
\fBsyslog\fR(3)
and is intended for internal use by Linux\-PAM and PAM service modules. The
\fIpriority\fR
argument is formed by ORing the facility and the level values as documented in the
\fBsyslog\fR(3)
manual page.
.PP
The
\fBpam_vsyslog\fR
function performs the same task as
\fBpam_syslog()\fR
with the difference that it takes a set of arguments which have been obtained using the
\fBstdarg\fR(3)
variable argument list macros.
.SH "SEE ALSO"
.PP

\fBpam\fR(8)
.SH "STANDARDS"
.PP
The
\fBpam_syslog\fR
and
\fBpam_vsyslog\fR
functions are Linux\-PAM extensions.
