.\"     Title: pam_authenticate
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_AUTHENTICATE" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_authenticate \- account authentication
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_appl.h>
.fi
.ft
.HP 21
.BI "int pam_authenticate(pam_handle_t\ *" "pamh" ", int\ " "flags" ");"
.SH "DESCRIPTION"
.PP
The
\fBpam_authenticate\fR
function is used to authenticate the user. The user is required to provide an authentication token depending upon the authentication service, usually this is a password, but could also be a finger print.
.PP
The PAM service module may request that the user enter their username vio the the conversation mechanism (see
\fBpam_start\fR(3)
and
\fBpam_conv\fR(3)). The name of the authenticated user will be present in the PAM item PAM_USER. This item may be recovered with a call to
\fBpam_get_item\fR(3).
.PP
The
\fIpamh\fR
argument is an authentication handle obtained by a prior call to pam_start(). The flags argument is the binary or of zero or more of the following values:
.TP 3n
PAM_SILENT
Do not emit any messages.
.TP 3n
PAM_DISALLOW_NULL_AUTHTOK
The PAM module service should return PAM_AUTH_ERR if the user does not have a registered authentication token.
.SH "RETURN VALUES"
.TP 3n
PAM_ABORT
The application should exit immediately after calling
\fBpam_end\fR(3)
first.
.TP 3n
PAM_AUTH_ERR
The user was not authenticated.
.TP 3n
PAM_CRED_INSUFFICIENT
For some reason the application does not have sufficient credentials to authenticate the user.
.TP 3n
PAM_AUTHINFO_UNVAIL
The modules were not able to access the authentication information. This might be due to a network or hardware failure etc.
.TP 3n
PAM_MAXTRIES
One or more of the authentication modules has reached its limit of tries authenticating the user. Do not try again.
.TP 3n
PAM_SUCCESS
The user was successfully authenticated.
.TP 3n
PAM_USER_UNKNOWN
User unknown to authentication service.
.SH "SEE ALSO"
.PP

\fBpam_start\fR(3),
\fBpam_setcred\fR(3),
\fBpam_chauthtok\fR(3),
\fBpam_strerror\fR(3),
\fBpam\fR(8)
