.\"     Title: pam_get_data
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/27/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_GET_DATA" "3" "06/27/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_get_data \- get module internal data
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <security/pam_modules.h>
.fi
.ft
.HP 17
.BI "int pam_get_data(const\ pam_handle_t\ *" "pamh" ", const\ char\ *" "module_data_name" ", const\ void\ **" "data" ");"
.SH "DESCRIPTION"
.PP
This function together with the
\fBpam_set_data\fR(3)
function is useful to manage module\-specific data meaningful only to the calling PAM module.
.PP
The
\fBpam_get_data\fR
function looks up the object associated with the (hopefully) unique string
\fImodule_data_name\fR
in the PAM context specified by the
\fIpamh\fR
argument. A successful call to
\fBpam_get_data\fR
will result in
\fIdata\fR
pointing to the object. Note, this data is
\fInot\fR
a copy and should be treated as
\fIconstant\fR
by the module.
.SH "RETURN VALUES"
.TP 3n
PAM_SUCCESS
Data was successful retrieved.
.TP 3n
PAM_SYSTEM_ERR
A NULL pointer was submitted as PAM handle or the function was called by an application.
.TP 3n
PAM_NO_MODULE_DATA
Module data not found or there is an entry, but it has the value NULL.
.SH "SEE ALSO"
.PP

\fBpam_end\fR(3),
\fBpam_set_data\fR(3),
\fBpam_strerror\fR(3)
