.\"     Title: pam_shells
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 11/06/2007
.\"    Manual: Linux-PAM Manual
.\"    Source: Linux-PAM Manual
.\"
.TH "PAM_SHELLS" "8" "11/06/2007" "Linux-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_shells - PAM module to check for valid login shell
.SH "SYNOPSIS"
.HP 14
\fBpam_shells\.so\fR
.SH "DESCRIPTION"
.PP
pam_shells is a PAM module that only allows access to the system if the users shell is listed in
\fI/etc/shells\fR\.
.PP
It also checks if
\fI/etc/shells\fR
is a plain file and not world writable\.
.SH "OPTIONS"
.PP
This module does not recognise any options\.
.SH "MODULE SERVICES PROVIDED"
.PP
The services
\fBauth\fR
and
\fBaccount\fR
are supported\.
.SH "RETURN VALUES"
.PP
PAM_AUTH_ERR
.RS 4
Access to the system was denied\.
.RE
.PP
PAM_SUCCESS
.RS 4
The users login shell was listed as valid shell in
\fI/etc/shells\fR\.
.RE
.PP
PAM_SERVICE_ERR
.RS 4
The module was not able to get the name of the user\.
.RE
.SH "EXAMPLES"
.PP

.sp
.RS 4
.nf
auth  required  pam_shells\.so
      
.fi
.RE
.sp
.SH "SEE ALSO"
.PP

\fBshells\fR(5),
\fBpam.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_shells was written by Erik Troan <ewt@redhat\.com>\.
