.\"     Title: pam_issue
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/17/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_ISSUE" "8" "06/17/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_issue \- PAM module to add issue file to user prompt
.SH "SYNOPSIS"
.HP 13
\fBpam_issue.so\fR [noesc] [issue=\fIissue\-file\-name\fR]
.SH "DESCRIPTION"
.PP
pam_issue is a PAM module to prepend an issue file to the username prompt. It also by default parses escape codes in the issue file similar to some common getty's (using \\x format).
.PP
Recognized escapes:
.TP 3n
\fB\\d\fR
current day
.TP 3n
\fB\\l\fR
name of this tty
.TP 3n
\fB\\m\fR
machine architecture (uname \-m)
.TP 3n
\fB\\n\fR
machine's network node hostname (uname \-n)
.TP 3n
\fB\\o\fR
domain name of this system
.TP 3n
\fB\\r\fR
release number of operating system (uname \-r)
.TP 3n
\fB\\t\fR
current time
.TP 3n
\fB\\s\fR
operating system name (uname \-s)
.TP 3n
\fB\\u\fR
number of users currently logged in
.TP 3n
\fB\\U\fR
same as \\u except it is suffixed with "user" or "users" (eg. "1 user" or "10 users")
.TP 3n
\fB\\v\fR
operating system version and build date (uname \-v)
.SH "OPTIONS"
.PP
.TP 3n
\fBnoesc\fR
Turns off escape code parsing.
.TP 3n
\fBissue=\fR\fB\fIissue\-file\-name\fR\fR
The file to output if not using the default.
.SH "MODULE SERVICES PROVIDED"
.PP
Only the
\fBauth\fR
service is supported.
.SH "RETURN VALUES"
.PP
.TP 3n
PAM_BUF_ERR
Memory buffer error.
.TP 3n
PAM_IGNORE
The prompt was already changed.
.TP 3n
PAM_SERVICE_ERR
A service module error occured.
.TP 3n
PAM_SUCCESS
The new prompt was set successfull.
.SH "EXAMPLES"
.PP
Add the following line to
\fI/etc/pam.d/login\fR
to set the user specific issue at login:
.sp
.RS 3n
.nf
        auth optional pam_issue.so issue=/etc/issue
      
.fi
.RE
.sp
.SH "SEE ALSO"
.PP

\fBpam.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_issue was written by Ben Collins <bcollins@debian.org>.
