.\"     Title: pam_warn
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/09/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_WARN" "8" "06/09/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_warn \- PAM module which logs all PAM items if called
.SH "SYNOPSIS"
.HP 12
\fBpam_warn.so\fR
.SH "DESCRIPTION"
.PP
pam_warn is a PAM module that logs the service, terminal, user, remote user and remote host to
\fBsyslog\fR(3). The items are not probed for, but instead obtained from the standard PAM items. The module always returns
\fBPAM_IGNORE\fR, indicating that it does not want to affect the authentication process.
.SH "OPTIONS"
.PP
This module does not recognice any options.
.SH "MODULE SERVICES PROVIDED"
.PP
The services
\fBauth\fR,
\fBaccount\fR,
\fBpassword\fR
and
\fBsession\fR
are supported.
.SH "RETURN VALUES"
.TP 3n
PAM_IGNORE
This module always returns PAM_IGNORE.
.SH "EXAMPLES"
.sp
.RS 3n
.nf
#%PAM\-1.0
#
# If we don't have config entries for a service, the
# OTHER entries are used. To be secure, warn and deny
# access to everything.
other auth     required       pam_warn.so
other auth     required       pam_deny.so
other account  required       pam_warn.so
other account  required       pam_deny.so
other password required       pam_warn.so
other password required       pam_deny.so
other session  required       pam_warn.so
other session  required       pam_deny.so
      
.fi
.RE
.SH "SEE ALSO"
.PP

\fBpam.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_warn was written by Andrew G. Morgan <morgan@kernel.org>.
