.\"     Title: pam_faildelay
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 12/06/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_FAILDELAY" "8" "12/06/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_faildelay \- Change the delay on failure per\-application
.SH "SYNOPSIS"
.HP 17
\fBpam_faildelay.so\fR [debug] [delay=\fImicroseconds\fR]
.SH "DESCRIPTION"
.PP
pam_faildelay is a PAM module that can be used to set the delay on failure per\-application.
.PP
If no
\fBdelay\fR
is given, pam_faildelay will use the value of FAIL_DELAY from
\fI/etc/login.defs\fR.
.SH "OPTIONS"
.TP 3n
\fBdebug\fR
Turns on debugging messages sent to syslog.
.TP 3n
\fBdelay=\fR\fB\fIN\fR\fR
Set the delay on failure to N microseconds.
.SH "MODULE SERVICES PROVIDED"
.PP
Only the
\fBauth\fR
service is supported.
.SH "RETURN VALUES"
.TP 3n
PAM_IGNORE
Delay was successful adjusted.
.TP 3n
PAM_SYSTEM_ERR
The specified delay was not valid.
.SH "EXAMPLES"
.PP
The following example will set the delay on failure to 10 seconds:
.sp
.RS 3n
.nf
auth  optional  pam_faildelay.so  delay=10000000
      
.fi
.RE
.sp
.SH "SEE ALSO"
.PP

\fBpam_fail_delay\fR(3),
\fBpam.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_faildelay was written by Darren Tucker <dtucker@zip.com.au>.
