.\"     Title: pam_env.conf
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/21/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_ENV.CONF" "5" "06/21/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_env.conf \- the environment variables config file
.SH "DESCRIPTION"
.PP
The
\fI/etc/security/pam_env.conf\fR
file specifies the environment variables to be set, unset or modified by
\fBpam_env\fR(8). When someone logs in, this file is read and the environment variables are set according.
.PP
Each line starts with the variable name, there are then two possible options for each variable DEFAULT and OVERRIDE. DEFAULT allows and administrator to set the value of the variable to some default value, if none is supplied then the empty string is assumed. The OVERRIDE option tells pam_env that it should enter in its value (overriding the default value) if there is one to use. OVERRIDE is not used, "" is assumed and no override will be done.
.PP

\fIVARIABLE\fR
[\fIDEFAULT=[value]\fR] [\fIOVERRIDE=[value]\fR]
.PP
(Possibly non\-existent) environment variables may be used in values using the ${string} syntax and (possibly non\-existent) PAM_ITEMs may be used in values using the @{string} syntax. Both the $ and @ characters can be backslash escaped to be used as literal values values can be delimited with "", escaped " not supported. Note that many environment variables that you would like to use may not be set by the time the module is called. For example, HOME is used below several times, but many PAM applications don't make it available by the time you need it.
.PP
The "\fI#\fR" character at start of line (no space at front) can be used to mark this line as a comment line.
.SH "EXAMPLES"
.PP
These are some example lines which might be specified in
\fI/etc/security/pam_env.conf\fR.
.PP
Set the REMOTEHOST variable for any hosts that are remote, default to "localhost" rather than not being set at all
.sp
.RS 3n
.nf
      REMOTEHOST     DEFAULT=localhost OVERRIDE=@{PAM_RHOST}
    
.fi
.RE
.PP
Set the DISPLAY variable if it seems reasonable
.sp
.RS 3n
.nf
      DISPLAY        DEFAULT=${REMOTEHOST}:0.0 OVERRIDE=${DISPLAY}
    
.fi
.RE
.PP
Now some simple variables
.sp
.RS 3n
.nf
      PAGER          DEFAULT=less
      MANPAGER       DEFAULT=less
      LESS           DEFAULT="M q e h15 z23 b80"
      NNTPSERVER     DEFAULT=localhost
      PATH           DEFAULT=${HOME}/bin:/usr/local/bin:/bin\\
      :/usr/bin:/usr/local/bin/X11:/usr/bin/X11
    
.fi
.RE
.PP
Silly examples of escaped variables, just to show how they work.
.sp
.RS 3n
.nf
      DOLLAR         DEFAULT=\\$
      DOLLARDOLLAR   DEFAULT=        OVERRIDE=\\$${DOLLAR}
      DOLLARPLUS     DEFAULT=\\${REMOTEHOST}${REMOTEHOST}
      ATSIGN         DEFAULT=""      OVERRIDE=\\@
    
.fi
.RE
.SH "SEE ALSO"
.PP

\fBpam_env\fR(8),
\fBpam.d\fR(5),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_env was written by Dave Kinchlea <kinch@kinch.ark.com>.
