.\"     Title: pam_echo
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/21/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_ECHO" "8" "06/21/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_echo \- PAM module for printing text messages
.SH "SYNOPSIS"
.HP 12
\fBpam_echo.so\fR [file=\fI/path/message\fR]
.SH "DESCRIPTION"
.PP
The
\fIpam_echo\fR
PAM module is for printing text messages to inform user about special things. Sequences starting with the
\fI%\fR
character are interpreted in the following way:
.TP 3n
\fI%H\fR
The name of the remote host (PAM_RHOST).
.TP 3n
\fB%h\fR
The name of the local host.
.TP 3n
\fI%s\fR
The service name (PAM_SERVICE).
.TP 3n
\fI%t\fR
The name of the controlling terminal (PAM_TTY).
.TP 3n
\fI%U\fR
The remote user name (PAM_RUSER).
.TP 3n
\fI%u\fR
The local user name (PAM_USER).
.PP
All other sequences beginning with
\fI%\fR
expands to the characters following the
\fI%\fR
character.
.SH "OPTIONS"
.TP 3n
\fBfile=\fR\fB\fI/path/message\fR\fR
The content of the file
\fI/path/message\fR
will be printed with the PAM conversion function as PAM_TEXT_INFO.
.SH "MODULE SERVICES PROVIDED"
.PP
All services are supported.
.SH "RETURN VALUES"
.TP 3n
PAM_BUF_ERR
Memory buffer error.
.TP 3n
PAM_SUCCESS
Message was successful printed.
.TP 3n
PAM_IGNORE
PAM_SILENT flag was given or message file does not exist, no message printed.
.SH "EXAMPLES"
.PP
For an example of the use of this module, we show how it may be used to print informations about good passwords:
.sp
.RS 3n
.nf
password optional pam_echo.so file=/usr/share/doc/good\-password.txt
password required pam_unix.so
      
.fi
.RE
.sp
.SH "SEE ALSO"
.PP

\fBpam.conf\fR(8),
\fBpam.d\fR(8),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
Thorsten Kukuk <kukuk@thkukuk.de>
