.\"     Title: namespace.conf
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.1 <http://docbook.sf.net/>
.\"      Date: 06/20/2007
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "NAMESPACE.CONF" "5" "06/20/2007" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
namespace.conf \- the namespace configuration file
.SH "DESCRIPTION"
.PP
This module allows setup of private namespaces with polyinstantiated directories. Directories can be polyinstantiated based on user name or, in the case of SELinux, user name, sensitivity level or complete security context. If an executable script
\fI/etc/security/namespace.init\fR
exists, it is used to initialize the namespace every time a new instance directory is setup. The script receives the polyinstantiated directory path and the instance directory path as its arguments.
.PP
The
\fI/etc/security/namespace.conf\fR
file specifies which directories are polyinstantiated, how they are polyinstantiated, how instance directories would be named, and any users for whom polyinstantiation would not be performed.
.PP
When someone logs in, the file
\fInamespace.conf\fR
is scanned where each non comment line represents one polyinstantiated directory with space separated fields as follows:
.PP

\fIpolydir\fR
\fI instance_prefix\fR
\fI method\fR
\fI list_of_uids\fR
.PP
The first field,
\fIpolydir\fR, is the absolute pathname of the directory to polyinstantiate. Special entry $HOME is supported to designate user's home directory. This field cannot be blank.
.PP
The second field,
\fIinstance_prefix\fR
is the string prefix used to build the pathname for the instantiation of <polydir>. Depending on the polyinstantiation
\fImethod\fR
it is then appended with "instance differentiation string" to generate the final instance directory path. This directory is created if it did not exist already, and is then bind mounted on the <polydir> to provide an instance of <polydir> based on the <method> column. The special string $HOME is replaced with the user's home directory, and $USER with the username. This field cannot be blank. The directory where polyinstantiated instances are to be created, must exist and must have, by default, the mode of 000. The requirement that the instance parent be of mode 000 can be overridden with the command line option
\fIignore_instance_parent_mode\fR
.PP
The third field,
\fImethod\fR, is the method used for polyinstantiation. It can take 3 different values; "user" for polyinstantiation based on user name, "level" for polyinstantiation based on process MLS level and user name, and "context" for polyinstantiation based on process security context and user name Methods "context" and "level" are only available with SELinux. This field cannot be blank.
.PP
The fourth field,
\fIlist_of_uids\fR, is a comma separated list of user names for whom the polyinstantiation is not performed. If left blank, polyinstantiation will be performed for all users.
.PP
In case of context or level polyinstantiation the SELinux context which is used for polyinstantiation is the context used for executing a new process as obtained by getexeccon. This context must be set by the calling application or
\fIpam_selinux.so\fR
module. If this context is not set the polyinstatiation will be based just on user name.
.PP
The "instance differentiation string" is <user name> for "user" method and <user name>_<raw directory context> for "context" and "level" methods. If the whole string is too long the end of it is replaced with md5sum of itself. Also when command line option
\fIgen_hash\fR
is used the whole string is replaced with md5sum of itself.
.SH "EXAMPLES"
.PP
These are some example lines which might be specified in
\fI/etc/security/namespace.conf\fR.
.sp
.RS 4
.nf
      # The following three lines will polyinstantiate /tmp,
      # /var/tmp and user's home directories. /tmp and /var/tmp
      # will be polyinstantiated based on the security level
      # as well as user name, whereas home directory will be
      # polyinstantiated based on the full security context and user name.
      # Polyinstantiation will not be performed for user root
      # and adm for directories /tmp and /var/tmp, whereas home
      # directories will be polyinstantiated for all users.
      #
      # Note that instance directories do not have to reside inside
      # the polyinstantiated directory. In the examples below,
      # instances of /tmp will be created in /tmp\-inst directory,
      # where as instances of /var/tmp and users home directories
      # will reside within the directories that are being
      # polyinstantiated.
      #
      /tmp     /tmp\-inst/               level      root,adm
      /var/tmp /var/tmp/tmp\-inst/   	level      root,adm
      $HOME    $HOME/$USER.inst/inst\- context
    
.fi
.RE
.PP
For the <service>s you need polyinstantiation (login for example) put the following line in /etc/pam.d/<service> as the last line for session group:
.PP
session required pam_namespace.so [arguments]
.PP
This module also depends on pam_selinux.so setting the context.
.SH "SEE ALSO"
.PP

\fBpam_namespace\fR(8),
\fBpam.d\fR(5),
\fBpam\fR(8)
.SH "AUTHORS"
.PP
The namespace.conf manual page was written by Janak Desai <janak@us.ibm.com>.
