.\"     Title: pam_exec
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/09/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_EXEC" "8" "06/09/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_exec \- PAM module which calls an external command
.SH "SYNOPSIS"
.HP 12
\fBpam_exec.so\fR [debug] [seteuid] [log=\fIfile\fR] \fIcommand\fR [\fI...\fR]
.SH "DESCRIPTION"
.PP
pam_exec is a PAM module that can be used to run an external command.
.SH "OPTIONS"
.PP
.TP 3n
\fBdebug\fR
Print debug information.
.TP 3n
\fBlog=\fR\fB\fIfile\fR\fR
The output of the command is appended to
\fIfile\fR
.TP 3n
\fBseteuid\fR
Per default pam_exec.so will execute the external command with the real user ID of the calling process. Specifying this option means the command is run with the effective user ID.
.SH "MODULE SERVICES PROVIDED"
.PP
The services
\fBauth\fR,
\fBaccount\fR,
\fBpassword\fR
and
\fBsession\fR
are supported.
.SH "RETURN VALUES"
.PP
.TP 3n
PAM_SUCCESS
The external command runs successfull.
.TP 3n
PAM_SERVICE_ERR
No argument or a wrong number of arguments were given.
.TP 3n
PAM_SYSTEM_ERR
A system error occured or the command to execute failed.
.TP 3n
PAM_IGNORE

\fBpam_setcred\fR
was called, which does not execute the command.
.SH "EXAMPLES"
.PP
Add the following line to
\fI/etc/pam.d/passwd\fR
to rebuild the NIS database after each local password change:
.sp
.RS 3n
.nf
        passwd optional pam_exec.so seteuid make \-C /var/yp
      
.fi
.RE
.sp
This will execute the command
.sp
.RS 3n
.nf
make \-C /var/yp
.fi
.RE
.sp
with effective user ID.
.SH "SEE ALSO"
.PP

\fBpam.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8)
.SH "AUTHOR"
.PP
pam_exec was written by Thorsten Kukuk <kukuk@thkukuk.de>.
