.\"     Title: pam_limits
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/17/2006
.\"    Manual: Linux\-PAM Manual
.\"    Source: Linux\-PAM Manual
.\"
.TH "PAM_LIMITS" "8" "06/17/2006" "Linux\-PAM Manual" "Linux\-PAM Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pam_limits \- PAM module to limit resources
.SH "SYNOPSIS"
.HP 14
\fBpam_limits.so\fR [change_uid] [conf=\fI/path/to/limits.conf\fR] [debug] [utmp_early]
.SH "DESCRIPTION"
.PP
The pam_limits PAM module sets limits on the system resources that can be obtained in a user\-session. Users of
\fIuid=0\fR
are affected by this limits, too.
.PP
By default limits are taken from the
\fI/etc/security/limits.conf\fR
config file.
.SH "OPTIONS"
.TP 3n
\fBchange_uid\fR
Change real uid to the user for who the limits are set up. Use this option if you have problems like login not forking a shell for user who has no processes. Be warned that something else may break when you do this.
.TP 3n
\fBconf=\fR\fB\fI/path/to/limits.conf\fR\fR
Indicate an alternative limits.conf style configuration file to override the default.
.TP 3n
\fBdebug\fR
Print debug information.
.TP 3n
\fButmp_early\fR
Some broken applications actually allocate a utmp entry for the user before the user is admitted to the system. If some of the services you are configuring PAM for do this, you can selectively use this module argument to compensate for this behavior and at the same time maintain system\-wide consistency with a single limits.conf file.
.SH "MODULE SERVICES PROVIDED"
.PP
Only the
\fBsession\fR
service is supported.
.SH "RETURN VALUES"
.TP 3n
PAM_ABORT
Cannot get current limits.
.TP 3n
PAM_IGNORE
No limits found for this user.
.TP 3n
PAM_PERM_DENIED
New limits could not be set.
.TP 3n
PAM_SERVICE_ERR
Cannot read config file.
.TP 3n
PAM_SESSEION_ERR
Error recovering account name.
.TP 3n
PAM_SUCCESS
Limits were changed.
.TP 3n
PAM_USER_UNKNOWN
The user is not known to the system.
.SH "FILES"
.TP 3n
\fI/etc/security/limits.conf\fR
Default configuration file
.SH "EXAMPLES"
.PP
For the services you need resources limits (login for example) put a the following line in
\fI/etc/pam.d/login\fR
as the last line for that service (usually after the pam_unix session line):
.sp
.RS 3n
.nf
#%PAM\-1.0
#
# Resource limits imposed on login sessions via pam_limits
#
session  required  pam_limits.so
    
.fi
.RE
.PP
Replace "login" for each service you are using this module.
.SH "SEE ALSO"
.PP

\fBlimits.conf\fR(5),
\fBpam.d\fR(8),
\fBpam\fR(8).
.SH "AUTHORS"
.PP
pam_limits was initially written by Cristian Gafton <gafton@redhat.com>
